--- 
addons: 
  packages: 
    - google-chrome-stable
  sources: 
    - google-chrome
before_script: 
  - "cd  ${TRAVIS_BUILD_DIR}/front-end/Project2"
cache: 
  directories: 
    - ./node_modules
dist: trusty
env: 
  - TEST_DIR=front-end/Project2
language: node_js
node_js: ~
notifications: 
  ? "-email"
  : roberte.flaherty@gmail.com
  script: pwd
script: 
  - "npm install && npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox"
