--- 
addons: 
  packages: 
    - google-chrome-stable
  sources: 
    - google-chrome
before_script: 
  - "cd  /home/travis/build/veitej/Project2-Gradebook/Project2"
cache: 
  directories: 
    - ./node_modules
dist: trusty
services: 
    - docker

language: node_js
node_js: node 
    
before_install: 
    - docker build -t veitej/gradebook .
script: 
  - npm install npm run test --watch=false --no-progress  - docker run -e CI=true veitej/gradebook npm run test -- --coverage
