dist: trusty
sudo: false

language: node_js
node_js:
  - '8'

addons:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

cache:
  directories:
    - ./node_modules

before_install:
- cd front-end/Project2

before_script:
 - cd front-end/Project2
 
 script:
 - npm install
