--- 
addons: 
  packages: 
    - google-chrome-stable
  sources: 
    - google-chrome
before_script: 
  - "cd  /home/travis/build/veitej/Project2-Gradebook/Project2"
cache: 
  directories: 
    - ./node_modules
dist: trusty
env: 
  - TEST_DIR=front-end/Project2
language: node_js
node_js: node
notifications: 
  ? "-email"
  : roberte.flaherty@gmail.com
  script: pwd
script: 
  - "npm install -g npm@'>=2.13.0 && npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox"
