--- 
addons: 
  packages: 
    - google-chrome-stable
  sources: 
    - google-chrome
before_script: 
  - "cd  /home/travis/build/veitej/Project2-Gradebook/Project2"
cache: 
  directories: 
    - ./node_modules
dist: trusty
language: node_js
node_js: 
  - node
notifications: 
   -email:
   - roberte.flaherty@gmail.com
script:
   - pwd
script: 
  - "npm install && npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox"
